[BasicSettings]
;COM,LPT,USB,NET
Port=USB

PrinterName=U80
;PrinterName=U80II

[PortSetting.COM]
PortName=COM1:

;1200,2400,4800,9600,19200,38400,57600,115200
BitsPerSecond=9600

;7,8
DataBits=8

;1,2
StopBits=1

;e=Even,n=None,o=Odd 
Parity=n

;p=DTR/DSR,x=Xon/Xoff
FlowControl=p

[PortSetting.LPT]
PortName=LPT1:

[PortSetting.USB]
;Be careful to modify this!
PortName=USB_U80_1
;PortName=USB_U80II_1

;Be careful to modify this!
USB_U80_1=496
;USB_U80II_1=496

[PortSetting.NET]
PortName=NET:
IPAddr=192.168.19.252
