INIVERSION=1

[LAYOUT]
RC_LAYOUTFORM=Main
RC_LANGUAGE=Select Language:
RC_PAPERSIZE=Paper Size:
RC_RADIO_ROTATE180=Rotate by 180 Degrees
RC_RADIO_ROTATENOMAL=Normal
RC_ROTATE=Rotate
RC_CHECK_ZOOM=Zoom Printing
RC_SCALE=Scale:
RC_PRINT_AS_IMAGE=Print all text as graphics image:
RC_RADIO_ASGRAPHICSYES=Yes
RC_RADIO_ASGRAPHICSNO=No
RC_DOCSETTING=Document Setting
RC_BUTTON_UPDATE=Update Language From Web
RC_BUTTON_LOG=Browse...
RC_BUTTON_VIEWER=Viewer
RC_CHECK_LOG=Record driver data
RC_STATIC_LOG=Driver LOG

CTEXT_BUTTON_LOG=Select the path of Log.
CTEXT_BUTTON_VIEWER=View the log.
CTEXT_CHECK_LOG=Record the driver log .
CTEXT_EDIT_LOG=The driver log dirctory.
CTEXT_RADIO_ASGRAPHICSYES=All the data will be printed as a graphic image.
CTEXT_RADIO_ASGRAPHICSNO=Disable 'All the data printed as a graphic image'.
CTEXT_RADIO_ROTATE180=Rotate the print direction of 180 degree as the example at the right side, and the image direction will be changed according to the settings.
CTEXT_RADIO_ROTATENOMAL=Set the print in normal direction as the example at the right side, and the image direction will be changed according to the settings.
CTEXT_CHECK_ZOOM=This configures reduced print.
CTEXT_SCALE=This configures reduced print.
CTEXT_LANGUAGE=You can select a language used for this properties dialog box.
CTEXT_PAPERSIZE=Select the paper size from list.
CTEXT_BUTTON_UPDATE=Update the language source.

[OPERATION]
RC_OPERATIONFORM=Operation
RC_STARTDOC=Start of Document
RC_STARTPAGE=Start of Page
RC_ENDPAGE=End of Page
RC_ENDDOC=End of Document
RC_STATIC_SDOC=Operation when document starts
RC_STATIC_SPAGE=Operation when page starts
RC_STATIC_ENDPAGE=Operation when page ends
RC_STATIC_ENDDOC=Operation when document ends

[UTILITY]
RC_UTILITYFORM=Utility
RC_SELFTEST=SelfTest
RC_STATIC_SELFTEST=Print a self-test page
RC_STATIC_CHECKCOMM=Check that communication settings is correct first
RC_STATIC_CUSTOMSIZE=User Defined Paper Size
RC_BUTTON_DELETE=Delete Paper Size
RC_BUTTON_SAVE=Save Paper Size
RC_STATIC_FORMNAME=Form Name:
RC_STATIC_FORMWIDTH=Width:
RC_STATIC_FORMHEIGHT=Height:
CTEXT_SELFTEST= Print Self-test page.
CTEXT_LIST_PAPERSIZE= List shows the user defined paper size. You can select one paper size from the list and edit its name, width and height, and you can also define a new paper size.
CTEXT_BUTTON_DELETE= Delete the selected user defined paper size in the list.
CTEXT_BUTTON_SAVE= Save user defined paper size. The user defined paper size will be saved if this button is clicked. If the paper size you edited is already in the list, then the width and height of the paper size will be rewritten.
CTEXT_EDIT_FORMNAME= Specify the name of paper size you want to save. The maximum length of the name is 18 characters.
CTEXT_EDIT_WIDTH= Specify the paper width.
CTEXT_EDIT_HEIGHT= Specify the paper height.

[DOWNLOAD]
RC_DOWNLOADFORM=Download
RC_STATIC_FWDOWNLOAD=File Download
RC_STATIC_DOWN_INFO=You can select various files to download to the printer, such as firmware files,font files
RC_BROWSE_FIREWARE=Browse
RC_DOWNLOAD_FIREWARE=Download
RC_STATIC_LOGODOWNLOAD=Logo Download
RC_STATIC_PREVIEW=Preview
RC_STATIC_HALFTONE=HalfTone
RC_STATIC_CONANDBRIGHT=Contrast and Brightness
RC_ORIGINAL=Original
RC_MONO=Transformation
RC_GRAY=Gray
RC_NONE=None
RC_DITHERM3=Dither M3
RC_DITHERM4=Dither M4
RC_DIFFUSE=Error Diffuse
RC_STATIC_CONTRA=Contrast:
RC_STATIC_BRIGHT=Brightness:
RC_LOGO_ADD=Add
RC_LOGO_DELETE=Delete
RC_LOGO_DOWNLOAD=Download all
RC_LOGO_CLEARALLLOGOS=Clear All Logos
RC_STATIC_DOWNOWNLOAD_NOTICE=Notice: Click "Transformation" or "Gray" in the "Preview" column to select the type of the logos before downloading.
RC_LOGOID=ID
RC_LOGONAME=Name
RC_LOGOPATH=Path
RC_BROWSEBOX=Open
CTEXT_EDIT_FIREWARE=Select the path of file that needs to be downloaded to printer.
CTEXT_BROWSE_FIREWARE=Select the path of file that needs to be downloaded to printer.
CTEXT_DOWNLOAD_FIREWARE=Download the selected file to printer.
CTEXT_LIST_LOGO=List displays the Logo that will be downloaded to printer. Select one of the Logo, and the function in image edit area will be enabled, then you can edit the Logo according to different demands. Attention: the Logo should be edit in the same format, if you edit one of the Logo, then the format of other Logos in the list will also be edited.
CTEXT_ORIGINAL=Provide preview of original logo image. Printer can receive Mono or gray scale logo, please select your needed image format before downloading.
CTEXT_MONO=Transform the Logo image type to be Mono image. If the original logo is chromatic, you can adjust the half-tone, contrast and brightness.
CTEXT_GRAY=Transform the Logo image type to be gray scale image. After selecting the gray scale image type, you can adjust the contrast and brightness.
CTEXT_NONE=Specify the dithering algorithm to be ¡°no dithering¡±. Image will display different dot matrix effect according to different dithering algorithm selected.
CTEXT_DITHERM3= Specify the dithering algorithm to be ¡°dithering M3¡±. Image will display different dot matrix effect according to different dithering algorithm selected.
CTEXT_DITHERM4= Specify the dithering algorithm to be ¡°dithering M4¡±. Image will display different dot matrix effect according to different dithering algorithm selected.
CTEXT_DIFFUSE= Specify the dithering algorithm to be ¡°error diffusion¡±. Image will display different dot matrix effect according to different dithering algorithm selected.
CTEXT_SLIDER_CONTRAST=Set the image contrast. You can change the image contrast via dragging this slider, contrast is reduced if drag this slider to left and contrast is increased if drag this slider to right.
CTEXT_SLIDER_BRIGHTNESS=Set the image brightness. You can change the image brightness via dragging this slider, brightness is dimming if drag this slider to left and brightness is brightened if drag this slider to right.
CTEXT_LOGO_ADD=Add one Logo to the list.
CTEXT_LOGO_DELETE=Delete one Logo from the list.
CTEXT_LOGO_DOWNLOAD=Download the Logo in the list to printer. All Logos in the printer will be cleared before downloading this Logo, and all the Logo in the list will be downloaded to the printer in sequence. These Logos will not be cleared after printer is reset or powered off.
CTEXT_LOGO_CLEARALLLOGOS=Clear all the Logos in printer.


[FONT]
RC_FONTFORM=Font
RC_STATIC_FONT_NOTICE=Select this font size in the application. 
RC_RONT_TREETITLE=Printer Fonts and Font Sizes

[VERSION]
RC_VERSIONFORM=Version
RC_STATIC_VER1=Printer Driver
RC_STATIC_VER2=Copyright (C) 2012-2019.
RC_STATIC_VER3=All Rights Reserved.
RC_STATIC_VER4=Product information:
RC_STATIC_VER5= Install version: V1.13                                                                  UI version: v1.13
RC_STATIC_VER6=Additional information:
RC_STATIC_VER7=
RC_STATIC_VER9=Warning: this program is protected by copyright law and international treaties. Unauthorized reproduction, distribution or portion of this program, may result in civil and criminal penalties, and will be prosecuted under the law.

[WATERMARK]
RC_WATERMARKFORM=Water Mark
RC_RADIO_NO=No Water Mark
RC_RADIO_IMAGE=Image Water Mark
RC_STATIC_WATERMARK_BMP=Bitmap:
RC_SELECT_PICTURE=Browse...
RC_RADIO_TEXT=Text Water Mark
RC_STATIC_WATERMARK_TEXT=Text:
RC_STATIC_WATERMARK_FONTTYPE=Font Type:
RC_STATIC_WATERMARK_FONTSTYLE=Font Style:
RC_STATIC_WATERMARK_FONTSTYLE1=Regular
RC_STATIC_WATERMARK_FONTSTYLE2=Italic
RC_STATIC_WATERMARK_FONTSTYLE3=Bold
RC_STATIC_WATERMARK_FONTSTYLE4=Bold Italic
RC_STATIC_WATERMARK_FONTSIZE=Font Size:
RC_STATIC_WATERMARK_ANGLE=Angle:
RC_STATIC_WATERMARK_POSITION=Print Position:
RC_STATIC_WATERMARK_POSITION1=Left-Top
RC_STATIC_WATERMARK_POSITION2=Center-Top
RC_STATIC_WATERMARK_POSITION3=Right-Top
RC_STATIC_WATERMARK_POSITION4=Left-Middle
RC_STATIC_WATERMARK_POSITION5=Center-Middle
RC_STATIC_WATERMARK_POSITION6=Right-Middle
RC_STATIC_WATERMARK_POSITION7=Left-Bottom
RC_STATIC_WATERMARK_POSITION8=Center-Bottom
RC_STATIC_WATERMARK_POSITION9=Right-Bottom
RC_STATIC_WATERMARK_POSITION10=Tiled
RC_STATIC_WATERMARK_SIZE=Size:
RC_STATIC_WATERMARK_BRIGHTNESS=Brightness:
CTEXT_RADIO_NO=Whether to use watermark printing function. Watermark printing is not used if this item is selected.
CTEXT_RADIO_IMAGE= Whether to use watermark printing function. Please select one bitmap to be as watermark of printing if this item is selected.
CTEXT_PICTURE_NAME=Select the path of watermark bitmap.
CTEXT_SELECT_PICTURE= Select the path of watermark bitmap.
CTEXT_RADIO_TEXT=Whether to use watermark printing function. Please select one text to be as watermark of printing if this item is selected. 
CTEXT_COMBO_TEXT=Select or edit the text used as watermark.
CTEXT_COMBO_FONTTYPE=Set the font type of text used as watermark. 
CTEXT_COMBO_FONTSTYLE= Set the font style of text used as watermark. 
CTEXT_EDIT_FONTSIZE=Set the font size of text used as watermark. 
CTEXT_SLIDER_ANGLE=Set the rotation angle of text used as watermark. 
CTEXT_COMBO_POSITION=Set the print position of watermark. 
CTEXT_SLIDER_SIZE=Set the zoom size of watermark.
CTEXT_SLIDER_LIGHT=Set the brightness of watermark.

[1DCODE]
RC_1DCODEFORM=1D Code
RC_STATIC_1DCODE_FONTNAME=Font Name:
RC_STATIC_1DCODE_TYPE=Type:
RC_STATIC_1DCODE_WIDTH=Element Width:
RC_STATIC_1DCODE_HEIGHT=Element Height:
RC_STATIC_1DCODE_POINT=point
RC_STATIC_1DCODE_NOTICE=Select this font size in the application.
RC_STATIC_1DCODE_POSITION=HRI Position:
RC_STATIC_1DCODE_POSITION1=Not printed
RC_STATIC_1DCODE_POSITION2=Above the barcode
RC_STATIC_1DCODE_POSITION3=Below the barcode
RC_STATIC_1DCODE_POSITION4=Both above and below the barcode
RC_STATIC_1DCODE_HRIFONT=HRI Font:
RC_STATIC_GENERALBARCODE=General Bar Code
RC_STATIC_1DCODE_GSDATABAR=GS1 DataBar
RC_STATIC_1DCODE_GSTYPE=Type:
RC_RADIO_Independence1=Independence
RC_RADIO_Complex1=Composite
RC_STATIC_1DCODE_GSEWIDTH=Element Width:
RC_STATIC_1DCODE_GSRHEIGHT=Row Height:
RC_STATIC_1DCODE_GS2DRHEIGHT=2D Row Height:
RC_STATIC_1DCODE_GSSHEIGHT=Separator Height:
RC_STATIC_1DCODE_HRI=HRI:
RC_CMB_HRI1=Primary and Secondary Data
RC_CMB_HRI2=Primary Data
RC_CMB_HRI3=Secondary Data
RC_CMB_HRI4=None
RC_STATIC_1DCODE_AAISTD=Expansion:
RC_CMB_AI1=None
RC_CMB_AI2=Application Identifier Specification to Data
RC_STATIC_1DCODE_PRINT=Test Print
RC_STATIC_1DCODE_DATA=Data:
RC_BUTTON_PRINT=Print
CTEXT_FONTNAME=Select the barcode font from the drop-down list.
CTEXT_BARCODETYPE=Select the barcode type from the drop-down list.
CTEXT_EDIT_WIDTH1D= Specify the element width of barcode. The unit of width is dot, available range is 2-6.
CTEXT_EDIT_HEIGHT1D=Specify the element height of barcode. The unit of height is dot, available range is 1-255.
CTEXT_HRIPOSITION=Select the print position of HRI characters from the drop-down list.
CTEXT_FONTA=Specify the font type of HRI character is FONT A. This item is disabled if ¡°HRI Position¡± is selected to be ¡° Not printed¡±.
CTEXT_FONTB= Specify the font type of HRI character is FONT B. This item is disabled if ¡°HRI Position¡± is selected to be ¡° Not printed¡±.
CTEXT_EDIT_PRINT=Input the data used for print test.
CTEXT_BUTTON_PRINT=Print the test data.
CTEXT_RADIO_Independence1=Specify the barcode to be independent barcode.
CTEXT_RADIO_Complex1= Specify the barcode to be complex barcode.
CTEXT_EDIT_GS1WIDTH= Specify the element width of barcode. The unit of width is dot, available range is 1-6.
CTEXT_EDIT_GS1HEIGHT= Specify the element height of barcode. The unit of width is dot, available range is 2-250.
CTEXT_EDIT_ComplexHEIGHT=Specify the basic element height of two-dimensional barcode symbol in complex barcode. This item is enabled only when the TYPE of COMPLEX is selected. The unit of height is dot, available range is 1-10.
CTEXT_EDIT_SeparatorHEIGHT=Specify the height of separator. The available range is 1-10.
CTEXT_CMB_HRI=Specify the print content of HRI characters.
CTEXT_CMB_AI=Specify whether to use application identifiers. This item is enabled only when the barcode type is GS1 DataBar Expanded.


[2DCODE]
RC_2DCODEFORM=2D Code
RC_STATIC_2DCODE_FONTNAME=Font Name:
RC_STATIC_2DCODE_TYPE=Type:
RC_STATIC_2DCODE_POINT=point
RC_STATIC_2DCODE_NOTICE=Select this font size in the application.
RC_STATIC_2DCODE_COLUMN=Column:
RC_STATIC_2DCODE_ELEMENTWIDTH=Element Width:
RC_STATIC_2DCODE_ROW=Row:
RC_STATIC_2DCODE_ELEMENTHEIGHT=Element Height:
RC_STATIC_2DCODE_ERRORCOR=Error Correction:
RC_STATIC_2DCODE_ERRORCOR1=Error Correction Level 0
RC_STATIC_2DCODE_ERRORCOR2=Error Correction Level 1
RC_STATIC_2DCODE_ERRORCOR3=Error Correction Level 2
RC_STATIC_2DCODE_ERRORCOR4=Error Correction Level 3
RC_STATIC_2DCODE_ERRORCOR5=Error Correction Level 4
RC_STATIC_2DCODE_ERRORCOR6=Error Correction Level 5
RC_STATIC_2DCODE_ERRORCOR7=Error Correction Level 6
RC_STATIC_2DCODE_ERRORCOR8=Error Correction Level 7
RC_STATIC_2DCODE_ERRORCOR9=Error Correction Level 8
RC_STATIC_2DCODE_GSDATABAR=GS1 DataBar
RC_STATIC_2DCODE_GSTYPE=Type:
RC_RADIO_Independence=Independence
RC_RADIO_Complex=Composite
RC_STATIC_2DCODE_GSEWIDTH=Element Width:
RC_STATIC_2DCODE_GS2DRHEIGHT=2D Row Height:
RC_STATIC_2DCODE_GSRHEIGHT=Row Height:
RC_STATIC_2DCODE_GSSHEIGHT=Separator Height:
RC_STATIC_2DCODE_GSSNUMBER=Segment Number:
RC_STATIC_2DCODE_GSHRI=HRI:
RC_IDC_CMB_HRI21=Primary and Secondary Data
RC_IDC_CMB_HRI22=Primary Data
RC_IDC_CMB_HRI23=Secondary Data
RC_IDC_CMB_HRI24=None
RC_STATIC_2DCODE_GSAAISTD=Expansion:
RC_IDC_CMB_AI21=None
RC_IDC_CMB_AI22=Application Identifier Specification to Data
RC_STATIC_2DCODE_PRINT=Test Print
RC_STATIC_2DCODE_DATA=Data:
RC_BUTTON_PRINT2D=Print
RC_STATIC_2DCODE_PDF417=PDF417
RC_STATIC_2DCODE_QR=QR
RC_STATIC_2DCODE_QREWIDTH=Element Width:
RC_STATIC_2DCODE_QRLMODE=Language mode:
RC_CMB_FONTMODE1=Chinese
RC_CMB_FONTMODE2=Japanese
RC_STATIC_2DCODE_QRMODE=Model:
RC_STATIC_2DCODE_QRECORRECTION=Error Correction:
CTEXT_FONTNAME2D= Select the barcode font from the drop-down list.
CTEXT_BARCODETYPE2D=Select the barcode type from the drop-down list.
CTEXT_RADIO_Independence=Specify the barcode type to be independent barcode.
CTEXT_RADIO_Complex=Specify the barcode type to be complex barcode.
CTEXT_EDIT_GS1WIDTH2= Specify the element width of barcode. The unit of width is dot, available range is 1-6.
CTEXT_EDIT_GS1HEIGHT2= Specify the element height of barcode. The unit of width is dot, available range is 2-250.
CTEXT_EDIT_ComplexHEIGHT2= Specify the basic element height of two-dimensional barcode symbol in complex barcode. This item is enabled only when the TYPE of COMPLEX is selected. The unit of height is dot, available range is 1-10.
CTEXT_EDIT_SeparatorHEIGHT2= Specify the height of separator. The available range is 1-10.
CTEXT_EDIT_SECTIONNUM=Specify the section number of barcode symbol per line. This parameter needs to be set only when the barcode type is GS1 DataBar Expanded Stacked. Available range for independent expanded stacked barcode is 2-20, and available range for complex expanded stacked barcode is 4-20.
CTEXT_CMB_HRI2= Specify the print content of HRI characters.
CTEXT_CMB_AI2= Specify whether to use application identifiers. This item is enabled only when the barcode type is GS1 DataBar Expanded Stacked.
CTEXT_EDIT_PRINT2D= Input the data used for print test.
CTEXT_BUTTON_PRINT2D= Print the test data.
CTEXT_EDIT_COLUMN=Specify the column of barcode. The available range is 1-30.
CTEXT_EDIT_WIDTH2D= Specify the element width of barcode. The unit of width is dot, available range is 1-7.
CTEXT_EDIT_ROW=Specify the row of barcode. The available range is 3-90.
CTEXT_EDIT_HEIGHT2D= Specify the element height of barcode. The unit of width is dot, available range is 2-25.
CTEXT_ERRORCORRECTIONLEVEL=Specify the error correction level.
CTEXT_EDIT_QRWIDTH= Specify the element width of barcode. The unit of width is dot, available range is 1-24.
CTEXT_CMB_FONTMODE=Select language pattern from the drop-down list.
CTEXT_CMB_TYPE=Select the barcode mode from the drop-down list.
CTEXT_CMB_ERROR=Select the error correction level from the drop-down list.

[DOCUMENT]
RC_DOCUMENT_STARTDOC=Start Document Operation
RC_DOCUMENT_STARTPAGE=Start Page Operation
RC_DOCUMENT_ENDPAGE=End Page Operation
RC_DOCUMENT_ENDDOC=End Document Operation
RC_SEND_COMMAND=Send Command      [Example:1D 56 42 00]
RC_OPEN_DRAWER=Open Drawer
RC_OPENDRAWER1=No Cash Drawer
RC_OPENDRAWER2=Cash Drawer #1 Waiting 10ms
RC_OPENDRAWER3=Cash Drawer #1 Waiting 20ms
RC_OPENDRAWER4=Cash Drawer #1 Waiting 40ms
RC_OPENDRAWER5=Cash Drawer #1 Waiting 60ms
RC_OPENDRAWER6=Cash Drawer #2 Waiting 10ms
RC_OPENDRAWER7=Cash Drawer #2 Waiting 20ms
RC_OPENDRAWER8=Cash Drawer #2 Waiting 40ms
RC_OPENDRAWER9=Cash Drawer #2 Waiting 60ms
RC_OPENDRAWER10=Cash Drawer #1+#2 Waiting 10ms
RC_OPENDRAWER11=Cash Drawer #1+#2 Waiting 20ms
RC_OPENDRAWER12=Cash Drawer #1+#2 Waiting 40ms
RC_OPENDRAWER13=Cash Drawer #1+#2 Waiting 60ms
RC_ORDER_MESSENGER=Herald
RC_ORDERMESSENGER1=Enable
RC_ORDERMESSENGER2=Disable
RC_STATIC_OPERATION_BUZZER=Buzzer and Volume:
RC_OPERATION_BUZZER1=Beep off
RC_OPERATION_BUZZER2=Beep one
RC_OPERATION_BUZZER3=Beep three
RC_OPERATION_BUZZER4=Beep five
RC_OPERATION_BUZZER5=Beep ten
RC_OPERATION_BUZZER6=Beep twenty
RC_STATIC_BUZZER_VOLUME=Buzzer Volume:
RC_STATIC_OPERATION_FEED=Paper Feed:
RC_FEEDTOPOSITION=Feed to cut position before cut
RC_PAPERCUT=Paper Cut:
RC_PAPER_CUT1=No Cut
RC_PAPER_CUT2=Partial Cut
RC_PAPER_CUT3=Full Cut
RC_STATIC_OPERATION_LOGO=Print Logo:
RC_PRINT_LOGO1=Not Print Logo
RC_PRINT_LOGO2=Print Logo1
RC_PRINT_LOGO3=Print Logo2
RC_PRINT_LOGO4=Print Logo3
RC_PRINT_LOGO5=Print Logo4
RC_PRINT_LOGO6=Print Logo5
RC_PRINT_LOGO7=Print Logo6
RC_PRINT_LOGO8=Print Logo7
RC_PRINT_LOGO9=Print Logo8
RC_PRINT_LOGO10=Print Logo9
RC_STATIC_OPERATION_ALIGN=Align:
RC_LEFT=Left
RC_CENTERED=Centered
RC_RIGHT=Right
RC_STATIC_OPERATION_POSITION=Position:
RC_BEFORE_CUT=Before Cut
RC_AFTER_CUT=After Cut
RC_OPERATION_DEFAULT=Default
RC_OPERATION_OK=OK
RC_OPERATION_CANCEL=Cancel
CTEXT_SEND_COMMAND=The command input column is enabled if this item is selected. Edit command which needs to be sent in the input column, this command will be sent at the document corresponding position.
CTEXT_EDIT=Edit the command which needs to be sent in the input column.
CTEXT_OPEN_DRAWER=Parameter of cash drawer can be set after selecting this item, and printer will control the cash drawer at document corresponding position.
CTEXT_OPENDRAWER=Select the cash drawer number and pulse time for opening.
CTEXT_ORDER_MESSENGER=The print messenger can be set after selecting this item. The print messenger will give the prompts you needed at the document corresponding position.
CTEXT_ORDERMESSENGER=Set the print messenger status (on/off).
CTEXT_BUZZER=Whether to enable the buzzer, and set the buzzer beep time.
CTEXT_BUZZERVOLUME=Set the volume of buzzer. This item is only enabled when the buzzer is on.
CTEXT_PAPER_FEED=Set paper feed distance. Print blank for the distance needed at the document corresponding position.
CTEXT_FEEDTOPOSITION=Feed paper to the cut position before cutting. After selecting this item, the print content will be sent out completely to avoid being cut off.
CTEXT_PAPER_CUT=Set the paper cut type(full cut / partial cut / no cut).
CTEXT_PRINT_LOGO=Set the serial number of Logo to be printed. These Logos are bitmaps stored in the Flash of printer, please confirm the needed Logo are stored in the printer before using these Logos.
CTEXT_LEFT=Select the Logo alignment mode to be left justification.
CTEXT_CENTERED= Select the Logo alignment mode to be center justification.
CTEXT_RIGHT= Select the Logo alignment mode to be right justification.
CTEXT_BEFORE_CUT=Select the Logo to be print before paper cut.
CTEXT_AFTER_CUT=Select the Logo to be print after paper cut.
CTEXT_IDDEFAULT=Recovery the optional items in this interface to be default.
CTEXT_IDOK=Confirm your settings.
CTEXT_IDCANCEL=Cancel your settings.

[COMPROPERTY]
RC_COMPROPERTY=COM Properties
RC_PORTSETTING=Port Settings
RC_COMSETTING=COM Settings
RC_STATIC_BAUDRATE=&Bits per second:
RC_STATIC_DATABITS=&Data bits:
RC_STATIC_PARITY=&Parity:
RC_STATIC_STOPBITS=&Stop bits:
RC_STATIC_FLOWCTRL=&Flow control:
RC_CB_PARITY_EVEN=Even
RC_CB_PARITY_ODD=Odd
RC_CB_PARITY_NONE=None
RC_CB_PARITY_MARK=Mark
RC_CB_PARITY_SPACE=Space
RC_CB_CLOWCTRL_HARDWARE=Hardware
RC_CB_CLOWCTRL_NONE=None

RC_COMCONFIGURATE=Config
RC_CONFIGCOMPORT=Configure COM Port
RC_STATIC_TIMEOUT=&Transmission Retry(MSEL):
RC_ERRORHANDLING=Print Error Handling
RC_STATIC_ERRORHANDLING=&Delete Print Job On Error:
RC_CB_ERROR_YES=Yes
RC_CB_ERROR_NO=No

[USBPROPERTY]
RC_USBCONFIGURATE=USB Properties
RC_CONFIGUSBPORT=Configure USB Port
RC_STATIC_TIMEOUTUSB=&Transmission Retry(sec.):
RC_ERRORHANDLINGUSB=Print Error Handling
RC_STATIC_ERRORHANDLINGUSB=&Delete Print Job On Error:
RC_CB_ERRORUSB_YES=Yes
RC_CB_ERRORUSB_NO=No
RC_USBCONFIGURATE_OK=&OK
RC_USBCONFIGURATE_CANCEL=&Cancel

[GPD]
RC_DENSITY=Print Density
RC_DENSITY_INDEX=Density
[DRIVERLOG]
RC_BTN_BOTTOM=BOTTOM
RC_BTN_TOP=TOP
RC_BTN_NEXT=NEXT
RC_BTN_BACK=BACK
RC_GROUP_PRINT=Print
RC_GROUP_PRINTER=Printer:
RC_ADDNEWLOG=Add new log
RC_BTN_EXIT=Exit
RC_RADIO_TODAY=Print this log
RC_RADIO_TOTAL=Print log of this day
RC_DRVNAME=U80
RC_PRNWIDTH=76
RC_PRNPOINT=580
MB_NOTFOUNDFILE=Not found file.
MB_LODAIMAGEERROR=Load image failed!
MB_LOGERROR=The printer dirver log is error!
RC_SELECTFILE=Please select driver log file path:

[MessageBox]
MB_INFORMATION=Information
MB_WARNING=Warning
MB_ERROR=Error
MB_2DCODE_ERROR1=BarCode data error!
MB_1DCODE_ERROR1=BarCode data error!
MB_WATERMARK_ERROR1=The specified file does not exist!
MB_WATERMARK_ERROR2=Please check if user has administrator privileges!
MB_WATERMARK_ERROR4=The bitmap you selected is too big!
MB_WATERMARK_ERROR5=Make sure the specified bitmap is 1/8/24/ bits!
MB_WATERMARK_ERROR6=No filename is specified!
MB_WATERMARK_INFORMATION1=All Text will be printed as graphics image!
MB_LAYOUT_INFORMATION1=All Text will be printed as graphics image!
MB_OPERATION_ERROR1=Command length error!

MB_UTILITY_ERROR1=Set custom paper size failed!
MB_DOWNLOAD_ERROR1=Fail to open the selected file!
MB_DOWNLOAD_ERROR2=Failed to get data from the file!
MB_DOWNLOAD_ERROR3=The image is too big. Its resolution must be less than 1024 * 768 Bytes!
MB_DOWNLOAD_ERROR4=The total counts of the logos should be less than 10!
MB_DOWNLOAD_ERROR5=Please select logos first!
MB_DOWNLOAD_ERROR6=Failed to get the size of logo!
MB_DOWNLOAD_ERROR7=The total sizes of all the logos is greater 96K!
MB_DOWNLOAD_ERROR8=Failed to get the size of the selected file!
MB_DOWNLOAD_ERROR9=Failed to Alloc the required memory!
MB_DOWNLOAD_ERROR10=Failed to set the file point to the head of the file!

MB_COM_INFORMATION1=Please restart the printer. The config will begin to take effect.
MB_LAYOUT_VIEWER = Not fount LOGViewer!